name       : mock
version    : 1.2.12
release    : 7
source     :
    - https://github.com/rpm-software-management/mock/archive/mock-1.2.12.tar.gz : cc13e93e969a145497f33484807d1fb06ab08880814229bc39bbe06d9c197c0d
license    : GPL-2.0-or-later
component  : programming.tools
summary    : RPM Chroot builder
description: |
    RPM Chroot builder
rundeps    :
    - usermode
    - python-requests
    - yum
    - rpm
    - lvm2
    - createrepo_c
    - btrfs-progs
    - yum-utils
    - yum-metadata-parser
    - pigz
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/mock.conf $installdir/%libdir%/sysusers.d/mock.conf
    # ensure mock privileges actually work..
    ln -sv /usr/bin/consolehelper $installdir/usr/bin/mock
