name       : mock
version    : 1.2.12
release    : 3
source     :
    - https://git.fedorahosted.org/cgit/mock.git/snapshot/mock-1.2.12.tar.xz : 4bb5617d9f187aa54983a5798b587138f1871adcfdd8ec510089f4439ada15e5
license    : GPL-2.0
summary    : RPM Chroot builder
description: |
    RPM Chroot builder
rundeps    :
    - usermode
    - python-requests
    - yum
    - rpm
    - lvm2
    - createrepo_c
    - btrfs-progs
    - yum-utils
    - yum-metadata-parser
setup      : |
    ./autogen.sh
    %configure
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/mock.conf $installdir/%libdir%/sysusers.d/mock.conf
    # ensure mock privileges actually work..
    ln -sv /usr/bin/consolehelper $installdir/usr/bin/mock
